#!/bin/sh
set -eu

usage() {
  cat <<'EOF'
Usage: sh ./shells/build-all.sh

Cross-compiles Coral for common OS/ARCH targets with CGO disabled.
Outputs into ./build/.

Targets:
  windows/amd64  -> coral-windows-amd64.exe
  linux/amd64    -> coral-linux-amd64
  linux/arm64    -> coral-linux-arm64
  darwin/amd64   -> coral-darwin-amd64
  darwin/arm64   -> coral-darwin-arm64

Note: windows/386 and linux/386 are omitted — github.com/larksuite/oapi-sdk-go/v3
(service/drive ListFileIterator uses math.MaxInt64 as int, which overflows on 32-bit).
EOF
}

case "${1:-}" in
  "" ) ;;
  -h|--help) usage; exit 0 ;;
  *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
esac

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
cd "$ROOT_DIR"

echo "===> Running time usage check (shells/check-time.sh)"
sh "$SCRIPT_DIR/check-time.sh"

echo "===> Counting Go LOC (shells/count-go-loc.sh)"
sh "$SCRIPT_DIR/count-go-loc.sh"

echo "===> Generating src/env_help_gen.go from .env.template"
ENV_TEMPLATE=".env.template"
ENV_HELP_PATH="src/env_help_gen.go"

awk '
function esc(s) {
  gsub(/\\/, "\\\\", s)
  gsub(/"/, "\\\"", s)
  return s
}
BEGIN {
  pending = ""
  print "// Code generated by shells/build-all.sh; DO NOT EDIT."
  print "package main"
  print ""
  print "var _ = func() bool {"
  print "\tenvVarHelps = []EnvVarHelp{"
}
{
  line = $0
  sub(/\r$/, "", line)
  trimmed = line
  sub(/^[[:space:]]+/, "", trimmed)
  sub(/[[:space:]]+$/, "", trimmed)

  if (trimmed == "") {
    pending = ""
    next
  }

  if (substr(trimmed, 1, 1) == "#") {
    sub(/^#[[:space:]]*/, "", trimmed)
    if (pending == "") pending = trimmed
    else pending = pending " " trimmed
    next
  }

  if (trimmed ~ /^[A-Z0-9_]+[[:space:]]*=/) {
    key = trimmed
    sub(/[[:space:]]*=.*$/, "", key)
    if (key != "") {
      name = esc(key)
      desc = esc(pending)
      print "\t\t{ Name: \"" name "\", Description: \"" desc "\" },"
    }
    pending = ""
  }
}
END {
  print "\t}"
  print "\treturn true"
  print "}()"
}
' "$ENV_TEMPLATE" > "$ENV_HELP_PATH" 2>/dev/null || {
  cat > "$ENV_HELP_PATH" <<'EOF'
// Code generated by shells/build-all.sh; DO NOT EDIT.
package main

var _ = func() bool {
	envVarHelps = []EnvVarHelp{}
	return true
}()
EOF
}

go mod tidy

OUT_DIR="build"
mkdir -p "$OUT_DIR"

build_one() {
  goos=$1
  goarch=$2
  name_arch="$goarch"
  if [ "$goarch" = "386" ]; then
    name_arch="x86"
  fi

  out="$OUT_DIR/coral-$goos-$name_arch"
  if [ "$goos" = "windows" ]; then
    out="$out.exe"
  fi

  echo "===> Building: $goos/$goarch -> $out"
  CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" go build -o "$out" ./src
}

build_one windows amd64
build_one linux amd64
build_one linux arm64
build_one darwin amd64
build_one darwin arm64

echo "===> Done. Artifacts in: $OUT_DIR"

