param(
    [string]$Output = "coral.exe"
)

# 切到仓库根目录（shells 的上级）
Set-Location -Path "$PSScriptRoot\.."

# 在构建前执行时间使用静态检查，禁止裸 time.Now()
Write-Host "===> Running time usage check (shells/check-time.ps1)"
& "$PSScriptRoot\check-time.ps1"
if ($LASTEXITCODE -ne 0) {
    Write-Host "Time usage check failed. Abort build." -ForegroundColor Red
    exit 1
}

$buildDir = "build"
if (-not (Test-Path $buildDir)) {
    New-Item -ItemType Directory -Path $buildDir | Out-Null
}

$outputPath = Join-Path $buildDir $Output

Write-Host "===> Building Go agent: $outputPath"

# 从 .env.template 生成 src/env_help_gen.go（供 src/main.go 中的 --help 使用）
Write-Host "===> Generating src/env_help_gen.go from .env.template"
$envTemplatePath = ".env.template"
$envLines = @()
if (Test-Path $envTemplatePath) {
    # 强制按 UTF-8 读取，避免中文注释在不同系统默认编码下乱码
    $envLines = Get-Content $envTemplatePath -Encoding UTF8 -ErrorAction Stop
} else {
    Write-Host "Warning: .env.template not found, generating empty env_help_gen.go" -ForegroundColor Yellow
}

$helps = @()
$pendingDesc = ""
foreach ($raw in $envLines) {
    $line = $raw.Trim()
    if ($line -eq "") {
        $pendingDesc = ""
        continue
    }
    if ($line.StartsWith("#")) {
        $text = $line.TrimStart("#").Trim()
        if ($pendingDesc -eq "") {
            $pendingDesc = $text
        } else {
            $pendingDesc = "$pendingDesc $text"
        }
        continue
    }

    $eqIndex = $line.IndexOf("=")
    if ($eqIndex -gt 0) {
        $key = $line.Substring(0, $eqIndex).Trim()
        if ($key -ne "") {
            $desc = $pendingDesc.Trim()
            $helps += [PSCustomObject]@{
                Name        = $key
                Description = $desc
            }
        }
        $pendingDesc = ""
    }
}

$goLines = @()
$goLines += "// Code generated by shells/build.ps1; DO NOT EDIT."
$goLines += "package main"
$goLines += ""
$goLines += "var _ = func() bool {"
$goLines += "	envVarHelps = []EnvVarHelp{"
foreach ($h in $helps) {
    $nameEsc = $h.Name.Replace('\', '\\').Replace('"', '\"')
    $descEsc = $h.Description.Replace('\', '\\').Replace('"', '\"')
    $goLines += "		{ Name: `"$nameEsc`", Description: `"$descEsc`" },"
}
$goLines += "	}"
$goLines += "	return true"
$goLines += "}()"

$envHelpPath = "src\\env_help_gen.go"
$goLines | Set-Content -Path $envHelpPath -Encoding UTF8

if (-not (Test-Path $envHelpPath)) {
    Write-Host "Failed to generate $envHelpPath" -ForegroundColor Red
    exit 1
}

go mod tidy
if ($LASTEXITCODE -ne 0) {
    Write-Host "go mod tidy failed." -ForegroundColor Red
    exit 1
}

go build -o $outputPath ./src
if ($LASTEXITCODE -ne 0) {
    Write-Host "Build failed." -ForegroundColor Red
    exit 1
}

Write-Host "Build succeeded: $outputPath" -ForegroundColor Green

